/**
 * OS-level sandboxing for commands an agent runs (gap-closure plan item 1.2,
 * 2026-09-26): the `sandbox:` declaration resolved into a policy
 * (`policy.ts`) and enforced by srt, `@anthropic-ai/sandbox-runtime`
 * (`srt.ts`). The Python package `webagents/sandbox/` is the twin; both are
 * pinned by `python/tests/fixtures/sandbox/srt.json`.
 *
 * THE POINT, in one sentence: an allow-list decides what the model ASKED FOR,
 * and a kernel sandbox decides what the process may TOUCH. Only the second is
 * a boundary. Four rules: wrap each command, never the agent process; fail
 * closed when a file declares `sandbox:` and the engine is missing; realpath
 * every path; pin the sandbox binaries by absolute path.
 */

export {
  AGENT_FILE_PATTERNS,
  CREDENTIAL_DIRS,
  DEFAULT_PRESET,
  ENV_NO_SANDBOX,
  ESCALATION_DENY,
  HOST_GROUPS,
  INERT_SANDBOX_FIELDS,
  OFF_PRESET,
  PRESETS,
  PROFILE_DIR_PATTERN,
  ROOT_READ_DENY,
  ROOT_READ_DENY_PATTERNS,
  SANDBOX_ACCEPTED_KEYS,
  SANDBOX_ALIASES,
  SANDBOX_FILES_KEYS,
  SANDBOX_KEYS,
  SANDBOX_NETWORK_KEYS,
  SCRATCH_DIR_NAME,
  SYSTEM_READ,
  SandboxDeclarationError,
  agentFileDenies,
  allowReads,
  checkNetworkEntry,
  closestKnown,
  defaultPolicy,
  denyReads,
  denyWrites,
  describePolicy,
  expandHosts,
  installWriteDenies,
  isSandboxOff,
  matchesAgentFilePattern,
  noSandboxRequested,
  parseSandboxDeclaration,
  policyFromDeclaration,
  profileDirDenies,
  rootReadDenies,
  sandboxState,
  similarity,
  unknownKeysMessage,
  type SandboxDeclaration,
  type SandboxOrigin,
  type SandboxPolicy,
} from './policy';

export {
  CLI_FROM_BUNDLED,
  DROPPED_ENV,
  ENV_CLI,
  ENV_NODE,
  FIX_CONTAINER,
  FIX_NAMESPACES,
  FIX_PLATFORM,
  FIX_SETUP_POINTER,
  FIX_TMPDIR,
  FIX_WINDOWS,
  INSTALL_INSIDE_DETAIL,
  INSTALL_INSIDE_FIX,
  INTERRUPTED_RESULT,
  KILL_GRACE_MS,
  LINUX_DEPS,
  LINUX_PACKAGES,
  NODE_FROM_PROCESS,
  NODE_MINIMUM,
  REFUSAL_HINTS,
  ROOT_OWNED_BIN_DIRS,
  SECRET_NAME_PARTS,
  SOCKET_PATH_LIMIT,
  SRT_NO_PROXY,
  SRT_PACKAGE,
  SRT_PATH,
  SRT_SOCKET_NAME,
  SRT_VERSION,
  UNAVAILABLE_TAIL,
  SandboxUnavailable,
  backendStatus,
  buildSettings,
  chooseNode,
  envFromDotenv,
  inContainer,
  installInsideCheck,
  linuxInstallFix,
  locateCli,
  locateEngine,
  locateSrt,
  namespaceRestriction,
  networkHost,
  noProxyEntryCovers,
  noProxyFor,
  parseNodeVersion,
  refusalHint,
  refusalKind,
  refusedHostsFromSrtLog,
  resetBackendStatus,
  runSandboxed,
  sandboxRequiredReason,
  scrubEnvironment,
  sdkInstallPaths,
  settingsBase,
  setupChecks,
  srtEnvironment,
  srtSocketProbe,
  tmpdirTooLong,
  unavailableFix,
  unavailableMessage,
  wrappedCommand,
  writeSettings,
  type BackendStatus,
  type RefusalKind,
  type SandboxRunOptions,
  type SandboxResult,
  type SetupCheck,
  type SrtLocation,
} from './srt';
